/* ACCOUNT SERVICE DATABASE LOAD */


--CREATE SEQUENCE CORE
DROP SEQUENCE IF EXISTS account_service_schema.USERS_IDUSER_SEQ;
CREATE SEQUENCE account_service_schema.USERS_IDUSER_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

--CREATE TABLES ACCOUNT SERVICE
CREATE TABLE account_service_schema.Users (
  idUser INTEGER NOT NULL DEFAULT NEXTVAL('account_service_schema.USERS_IDUSER_SEQ'),
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL
);
ALTER TABLE account_service_schema.Users ADD CONSTRAINT PKEY_BY_IDUSER PRIMARY KEY(idUser);

--SELECT TEST ACCOUNT SERVICE DATABASE
SELECT * FROM account_service_schema.Users;
